# Generated by Django 5.2 on 2025-04-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArbitrageOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_exchange", models.CharField(max_length=50)),
                ("sell_exchange", models.CharField(max_length=50)),
                ("buy_price", models.DecimalField(decimal_places=8, max_digits=18)),
                ("sell_price", models.DecimalField(decimal_places=8, max_digits=18)),
                ("profit", models.DecimalField(decimal_places=8, max_digits=18)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Arbitrage Opportunities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profit_threshold",
                    models.DecimalField(decimal_places=2, default=10, max_digits=10),
                ),
                (
                    "trade_amount",
                    models.DecimalField(decimal_places=6, default=0.01, max_digits=10),
                ),
                ("active", models.BooleanField(default=False)),
                ("symbol", models.CharField(default="BTC/USDT", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("api_key", models.CharField(max_length=200)),
                ("secret", models.CharField(max_length=200)),
            ],
        ),
    ]
