# Generated by Django 5.2 on 2025-04-03 05:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profit_threshold",
                    models.DecimalField(decimal_places=2, default=10, max_digits=10),
                ),
                (
                    "trade_amount",
                    models.DecimalField(decimal_places=6, default=0.01, max_digits=10),
                ),
                ("active", models.BooleanField(default=False)),
                ("symbol", models.CharField(default="BTC/USDT", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArbitrageOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("exchange1", models.CharField(max_length=50)),
                ("exchange2", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=20)),
                (
                    "price_diff",
                    models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
            ],
            options={
                "verbose_name_plural": "Arbitrage Opportunities",
                "indexes": [
                    models.Index(
                        fields=["symbol"], name="arbitrage_a_symbol_d64f60_idx"
                    )
                ],
            },
        ),
    ]
