# Generated by Django 5.2 on 2025-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arbitrage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangeconfig",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="exchangeconfig",
            name="secret",
        ),
        migrations.AddField(
            model_name="exchangeconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
